name: CI Documentation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5.4.0
        with:
          version: "latest"
          pyproject-file: "pyrpoject.toml"
          enable-cache: true

      - name: Install Dependencies
        run: |
          uv sync --all-groups

      - name: Check Sphinx Documentation build minimally
        working-directory: ./docs
        run: |
          uv run sphinx-build -E -W source build

      - name: Check for documentation style errors
        run: |
          uv run hatch run validate-docs
